# Generated by Django 4.0.2 on 2022-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAmoIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key_subdomain', models.CharField(max_length=255)),
                ('key_client_id', models.CharField(max_length=255)),
                ('key_client_secret', models.CharField(max_length=255)),
                ('key_redirect_url', models.CharField(max_length=255)),
                ('key_code', models.TextField(max_length=2000)),
                ('key_link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'KeyIntegration',
                'verbose_name_plural': 'KeyIntegration',
                'ordering': ['pk'],
            },
        ),
        migrations.DeleteModel(
            name='ApiLeads',
        ),
    ]
