# Generated by Django 4.0.2 on 2022-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_apiamointegration_delete_apileads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrftoken', models.CharField(max_length=255)),
                ('time_create', models.TimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CurrentToken',
                'verbose_name_plural': 'CurrentToken',
                'ordering': ['-time_create', 'pk'],
            },
        ),
    ]
