# Generated by Django 4.0.2 on 2022-02-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_currenttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentToken',
        ),
    ]
