# Generated by Django 4.0.2 on 2022-02-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_delete_currenttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsAllRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'FieldsAllRequest',
                'verbose_name_plural': 'FieldsAllRequest',
                'ordering': ['pk'],
            },
        ),
    ]
